// <auto-generated />
namespace EduZone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
<<<<<<<< HEAD:EduZone/Migrations/202306162006498_init.Designer.cs
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
            get { return "202306162006498_init"; }
========
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Post));
        
        string IMigrationMetadata.Id
        {
            get { return "202306231834515_Post"; }
>>>>>>>> master:EduZone/Migrations/202306231834515_Post.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
