// <auto-generated />
namespace EduZone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class post_com : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_com));
        
        string IMigrationMetadata.Id
        {
            get { return "202305270257520_post_com"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
