// <auto-generated />
namespace EduZone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Abdallah_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Abdallah_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202306231355207_Abdallah_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
